---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: topicosp1backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: topicosp1backend
    spec:
      containers:
      - name: topicosp1backend
        image: l0nkdev/topicosp1backend:v7
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: topicosp1backend
---
apiVersion: v1
kind: Service
metadata:
  name: topicosp1backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32002
  selector:
    app: topicosp1backend